### ISSUE TITLE
singularity instance.start depreicated in versions >= 3.0.0

### ISSUE THREAD

**Issue by Athanaseus** [ratt-ru/radiopadre-client#18]
The new way is `singularity instance start`

**Comment by o-smirnov** [comment]
It >=3.0 already widely available? Is there any downside to using the old command with 3.0+ for now?

Not all clusters have upgraded to Singularity 3.x, which why I hesitate to make the code incompatible with 2.x. I mean we could check versions and do if statements, but I'd rather avoid all that noodling around if I can.

**Comment by Athanaseus** [comment]
No downside that I know off, I just assumed since `CARACal` accommodates both some users might run into issues converting notebooks into `html`.
- I was just pointing it out, not sure if it's even widely used.
