### ISSUE TITLE
add optional dependency that will pull required containers at install

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/radiopadre-client#25]
Radio padre will try to pull the container images at runtime, but some systems, like the SA CHPC do not have an internet connection on compute nodes. So it would be nice to have a flag that can be triggered at install

**Comment by o-smirnov** [comment]
OK, I propose to implement it as
```
pip install radiopadre-client[pull_docker,pull_singularity]
```
One thing to note though, Caracal currently calls ``run-radiopadre`` with ``--update``, which triggers an image pull attempt anyway. Maybe we should disable this in a point release (or make it optional, configurable via the ``general`` section, and off by default).

Adding an ``--ignore-update-errors`` option (default true) to ``run-radiopadre`` would also help.

**Comment by o-smirnov** [comment]
Hmm, ``pip install radiopadre-client[pull_singularity]``, this is not the way. This can only be used to trigger extra pip dependencies, apparently the ``setup.py`` script never sees the extras flag, so there's no way to modify the post-install behaviour.

I'll provide ``run-radiopadre --pull-docker`` and ``run-radiopadre --pull-singularity`` options, but they'll have to be invoked explicitly somehow after the install.
