### ISSUE TITLE
Allow user to specify an alternative to the home directory as parent for .local and .radiopadre

### ISSUE THREAD

**Issue by gigjozsa** [ratt-ru/radiopadre-client#30]
https://github.com/ratt-ru/radiopadre-client/blob/6598f1c45ebe05afae24f9a60c80f8c955cf6fb4/radiopadre_client/backends/singularity.py#L40
and
https://github.com/ratt-ru/radiopadre-client/blob/6598f1c45ebe05afae24f9a60c80f8c955cf6fb4/radiopadre_client/backends/singularity.py#L111
If ``~`` could be replaced by a variable RADIOPADRE_HOME or RADIOPADRE_PARENT this would give the user the freedom to use something else and prevent storage problems on ~

**Comment by o-smirnov** [comment]
In principle, this is already implemented as the ``RADIOPADRE_DIR`` environment variable in rc12 (which I just merged).

In practice, you have spotted a bug I've missed -- I see that this directory is not propagated to a singularity container correctly. Possibly the same problem affects docker.
