### ISSUE TITLE
rendering of diagnostic plots hangs when going to next directory level

### ISSUE THREAD

**Issue by kendak333** [ratt-ru/radiopadre-client#44]
Not sure if this is an issue on my end or something else. When I run
`run-radiopadre oates:j2023L/output-j2023L/j2023L-std-progress-report.ipynb`
the notebook hangs during the Diagnostic Plots step - I added the print statement to make sure it was seeing the files.
![Screenshot from 2022-08-09 11-43-29](https://user-images.githubusercontent.com/33416498/183618164-608e9860-c231-46aa-b9de-8c6e07eb3818.png)

**Comment by o-smirnov** [comment]
Mind if I log in as you and give it a try myself?

**Comment by kendak333** [comment]
Sure, go ahead

**Comment by o-smirnov** [comment]
OK, could you please try the 1.2rc2 release? Either ``pip install radiopadre-client==1.2.rc2`` locally, or check out the ``b1.2.pre2`` branch of it locally and ``pip install -e``. In either case then run once with extra flags ``--update --venv-reinstall`` to update the remote end.

**Comment by kendak333** [comment]
That seems to have worked, thanks.
